## Numpy Fucntions

In [2]:
import numpy as np

In [3]:
#1. 1-D Array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
#2. 2-D Array
arr = np.array([[1,3,7],[2,4,6]])
arr 

array([[1, 3, 7],
       [2, 4, 6]])

In [6]:
#3. Array Indexing
arr = np.array([1,3,5,7,9])
print(arr[3])

7


In [7]:
#4. Array Slicing
arr = np.array([1,3,5,7,9])
print("1st SLice",arr[1:4])
print("2nd SLice",arr[4:])
print("3rd SLice",arr[:4])
print("4th SLice",arr[-3:-1])

1st SLice [3 5 7]
2nd SLice [9]
3rd SLice [1 3 5 7]
4th SLice [5 7]


In [8]:
#5. Array with data type
print(arr.dtype)

int64


In [10]:
#6. Copy
x = arr.copy()
x

array([1, 3, 5, 7, 9])

In [12]:
#7. View
arr = np.array([1,3,5,7,9])
x = arr.view()
print("arr:",arr)
print("x:",x)

arr: [1 3 5 7 9]
x: [1 3 5 7 9]


In [13]:
#8. base()
arr = np.array([1,3,5,7,9])
x = arr.copy()
y = arr.view()
print("x:",x.base)
print("y:",y.base)

x: None
y: [1 3 5 7 9]


In [14]:
#9. shape()
arr = np.array([[1,3,5,7],[2,4,6,8]])
print("Shape:",arr.shape)

Shape: (2, 4)


In [18]:
#10. reshape()
arr = np.array([1,3,5,7])
newarr = arr.reshape(2,2)
print("Reshaped array:",newarr)

Reshaped array: [[1 3]
 [5 7]]


In [20]:
#11. Flattening of arrays
arr = np.array([[1,3,5,7],[2,4,6,8]])
newarr = arr.reshape(-1)
print("Flattened array:",newarr)

Flattened array: [1 3 5 7 2 4 6 8]


In [50]:
#12. Iterating array
arr = np.array([[1,3],[2,4],[5,7],[6,8]])
for x in np.nditer(arr):
    print(x,end=' ')

1 3 2 4 5 7 6 8 

: 

In [22]:
#13. ndenumerate()
arr = np.array([1,3,5,7,9])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 3
(2,) 5
(3,) 7
(4,) 9


In [23]:
#14. concatenate()
arr1 = np.array([[1,3],[5,7]])
arr2 = np.array([[2,4],[6,8]])
newarr = np.concatenate((arr1, arr2),axis=1)
print("Concatenated array:",newarr)


Concatenated array: [[1 3 2 4]
 [5 7 6 8]]


In [24]:
#15. Joining using stack
arr1 = np.array([[1,3],[5,7]])
arr2 = np.array([[2,4],[6,8]])
newarr = np.stack((arr1, arr2),axis=1)
rowarr = np.hstack((arr1,arr2))
colarr = np.vstack((arr1,arr2))
hgtarr = np.dstack((arr1,arr2))

print("Stacking:",newarr)
print("Horizontal Stacking:",rowarr)
print("Vertical Stacking:",colarr)
print("Height Stacking:",hgtarr)

Stacking: [[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]
Horizontal Stacking: [[1 3 2 4]
 [5 7 6 8]]
Vertical Stacking: [[1 3]
 [5 7]
 [2 4]
 [6 8]]
Height Stacking: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
#16. split()
arr = np.array([1,3,5,7,9])
newarr = np.array_split(arr,3)
print(newarr)  

[array([1, 3]), array([5, 7]), array([9])]


In [29]:
#17. where()
arr = np.array([1,3,5,7,9])
x = np.where(arr == 7)
print("Element-wise comparison:",x)

Element-wise comparison: (array([3]),)


In [30]:
#18. sort()
arr = np.array([5,2,7,9,1,3,4])
print("Sorted array:",np.sort(arr))

Sorted array: [1 2 3 4 5 7 9]


In [33]:
#19. Random number
x = np.random.randint(100)
print("Random number:",x)

y = np.random.randint(10,size=5)
print("Random number:",y)

Random number: 96
Random number: [1 1 9 0 1]


In [34]:
#20. Trignonometric function
x = np.sin(np.pi/2)
x

np.float64(1.0)

In [35]:
#21. DEG to RAD
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
x

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [36]:
#22. Find angle
x = np.arcsin(1.0)
print("Angle:",np.rad2deg(x))

Angle: 90.0


In [37]:
#23. Hypotenuse
x = np.hypot(11,23)
x

np.float64(25.495097567963924)

In [38]:
#24. GCD
x = np.gcd(35,115)
x

np.int64(5)

In [39]:
#25. Difference
arr = np.array([10 ,15, 25, 5])
newarr = np.diff(arr)
print("Difference:",newarr)

Difference: [  5  10 -20]


In [41]:
#26. Product
arr = np.array([1,3,5,7,9])
arr = np.prod(arr)
print("Product:",arr)

Product: 945


In [42]:
#27. Find product
arr1 = np.array([1,3,7])
arr2 = np.array([2,4,6])
x = np.prod([arr1,arr2])
print("Product:",x)

Product: 1008


In [43]:
#28. Cumulative product
arr = np.array([1,3,5,7,9])
x = np.cumprod(arr)
print("Cumulative product:",x)

Cumulative product: [  1   3  15 105 945]


In [44]:
#29. Capitalize
print(np.char.capitalize('demon'))

Demon


In [45]:
#30. Title
print(np.char.title('demon slayer'))

Demon Slayer


In [47]:
#31. Lower
print(np.char.lower('DEMON'))

demon


In [49]:
#32. Replace
print(np.char.replace('I was a Demon','was','am'))

I am a Demon
